kind: Pod
apiVersion: v1
metadata:
  name: cypress-pod
  labels:
    app: cypress-pod
spec:
  containers:
  - name: file-copy
    image: ubuntu
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: shared-data
      mountPath: /test-results
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: "20m"
        memory: "100Mi"
  - name: cypress-pod
    image: cypress/included:12.0.2
    command:
      - /bin/sh
      - -c
      - |
        mkdir /testing
        cd /testing
        mkdir cypress
        cd cypress
        tar -xf /cypress-zipped/erabliereiu-cypress.tar -C /testing/cypress
        mv ErabliereIU/cypress/* .
        rm -r ErabliereIU/
        cp /cypress-config/tsconfig.json /testing/cypress/tsconfig.json
        cp /cypress-config/cypress.json /testing/cypress/cypress.json
        yarn add typescript
        cypress run --config video=false --reporter junit --reporter-options "mochaFile=/test-results/cypress-test-output-[hash].xml"
    # env:
    # - name: DEBUG
      # value: "cypress:*"
    volumeMounts:
    - name: cypress-file-zipped
      mountPath: /cypress-zipped
      readOnly: true
    - name: cypress-config
      mountPath: /cypress-config
      readOnly: true
    - name: shared-data
      mountPath: /test-results
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
  volumes:
  - name: cypress-file-zipped
    configMap:
      name: erabliereiu-cypress-files-zipped
  - name: cypress-config
    configMap:
      name: erabliereiu-cypress-config
  - name: shared-data
    emptyDir: {}