# this is a github action that reboot an azure webapp
# and then run the test script locally targeting the webapp
name: ErabliereAPI-Test-Demo

on: 
  workflow_run:
      workflows: ["ErabliereAPI-Image"]
      branches: [master]
      types: 
        - completed
  workflow_dispatch:

env:
  EXAMPLE: exemple

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with: # Set Azure credentials secret as an input
          creds: ${{ secrets.AZURE_DEMO_CREDENTIALS }}
          enable-AzPSSession: true

      - uses: actions/checkout@v2
      - name: Reboot the webapp
        run: |
          az webapp restart --name erabliereapi-demo --resource-group erabliereapi-demo
          sleep 35

      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: Postman/ErabliereAPI.postman_collection.json
          environment: Postman/ErabliereAPI-Demo.postman_environment.json
          reporters: '["cli","junit"]'

      - name: Install node
        uses: actions/setup-node@v2
        with:
            node-version: '18'

      - name: Install dependencies
        run: |
          cd ErabliereIU
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ErabliereIU
          config: video=false,baseUrl=https://erabliereapi-demo.azurewebsites.net
